### PR TITLE
Add order keys to qualifiers and references

### PR DESCRIPTION
**Pull request by itamargiv**

### CODE REVIEW

**Review by wiese — APPROVED** [review]

**Review by addshore — CHANGES_REQUESTED** [review]
So per the fact that these may be used sometimes by editing clients (maybe) should we also add theseinto the edit endpoint payloads (currently they are not there)

**Comment by wiese** [comment]
Would be nice if the example could show e.g. the property ids for `qualifiers-order` matching `qualifiers` but that does not seem easily possible the way we structure things.

Bildschirmfoto von 2020-09-23 16-22-52

**Comment by addshore** [comment]
> Would be nice if the example could show e.g. the property ids for `qualifiers-order` matching `qualifiers` but that does not seem easily possible the way we structure things.

I think the solution there would be going down the path of https://github.com/wmde/wikibase-rest-api-proposal/pull/65 and poviding some real wordlish examples

**Comment by itamargiv** [comment]
@addshore Made the requested changes, but now I see the risk of the "new" payloads and the "persisted" schamas falling out of sync, I will follow up with a seperate PR to rectify that and also continue with #65 to add meaningful examples

**Comment by addshore** [comment]
> @addshore Made the requested changes, but now I see the risk of the "new" payloads and the "persisted" schemas falling out of sync, I will follow up with a separate PR to rectify that and also continue with #65 to add meaningful examples

Follow up sounds great!

**Pull request merged**
