### PR TITLE
Flatten directories

### PR DESCRIPTION
**Pull request by itamargiv**
This is the second PR in the chain to ultimately separate item and property endpoints. In this PR We move all resources to the top level of the resources folder. Depends on #72

### CODE REVIEW

**Review by wiese — COMMENTED** [review]
I'm not sure about this. While it makes sense to think about resources instead of strictly paths, it is also true that some resources simply need 2 criteria to be identified. As such, seeing e.g. "labels" as a sibling of "entities" is strange to me. /my 2ct:

**Comment by addshore** [comment]
I'm quite on the fence about this one too.
Looking at the old and new (proposed) file structure my gut says I prefer the old one.
Having said that I don't have any concrete arguments in either direction.

**Comment by itamargiv** [comment]
> "seeing e.g. "labels" as a sibling of "entities" is strange to me" 

I get where you are coming from, however, for me the hierarchy between the resources is expressed in the path. The fact that one resource is included within the other doesn't change the fact that they are both resources that are accessed and manipulated nonetheless.

**Comment by wiese** [comment]
> hierarchy between the resources is expressed in the path.

True.

As a counter argument we could say that the info in the resource folders describe HTTP actions on these paths and as such are directly related to it (we are not talking about [data model] schemas here or comparable]).

But this is strictly internal organization and it allows for some deduplication without awkwardness so I could live with it.

**Review by wiese — APPROVED** [review]

**Pull request merged**
